/*	vdy_rt_work.c - generated by vm_gen_rt_work

	DO NOT EDIT
*/

const char* vdy_rt_work() {
	return ("");
}

const char* vdy_rt_regexp() {
	return ("(^((?!(SimCtrl|DYNA4_Reset|DYNA4_Signal_Access|DataDir|ParameterFiles)).)*$)");
}

